learning_foreign_languages/urls.py
"""Определяет схемы URL для learning_foreign_languages."""
from django.urls import path
from . import views

app_name = 'learning_foreign_languages'
urlpatterns = [
    # Домашняя страница
    path('', views.index, name='index'),
    #Вывод всех языков.
    path('languages/', views.languages, name='languages'),
    # Страница с подробной информацией по языку
    path('languages/<int:language_id>/', views.language, name='language')
]

learning_languages/urls.py
from django.urls import path, include
from django.contrib import admin


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('learning_foreign_languages.urls', namespace='learning_foreign_languages')),
]

learning_foreign_languages/models.py
from django.db import models

# Create your models here.
class Language(models.Model):
    """Язык, который изучает пользователь"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Возвращает строковое представление модели."""
        return self.text


class Vocabulary(models.Model):
    """Информация, изученная пользователем по языку"""
    language = models.ForeignKey(Language, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'vocabularies'

    def __str__(self):
        """Возвращает строковое представление модели"""

        if len(self.text) > 50:
            return self.text[:50] + "..."
        else:
            return self.text

learning_foreign_languages/views.py
from django.shortcuts import render
from .models import Language

# Create your views here.
def index(request):
    """Домашняя страница приложения Learning Languages"""
    return render(request, 'learning_foreign_languages/index.html')


def languages(request):
    """Выводит список языков"""
    languages = Language.objects.order_by('date_added')
    context = {'languages': languages}
    return render(request, 'learning_foreign_languages/languages.html', context)


def language(request, language_id):
    """Выводит один язык и все его записи"""
    language = Language.objects.get(id=language_id)
    vocabularies = language.vocabulary_set.order_by('-date_added')
    context = {'languages': languages, 'vocabularies': vocabularies}
    return render(request, 'learning_foreign_languages/languages.html', context)

learning_foreign_languages/templates/learning_foreign_languages/base.html
<p>
    <a href="{% url 'learning_foreign_languages:index' %}">Learning Languages</a> -
    <a href="{% url 'learning_foreign_languages:languages' %}">Languages</a>

</p>
{% block content %}{% endblock content %}

learning_foreign_languages/templates/learning_foreign_languages/index.html
{% extends "learning_foreign_languages/base.html" %}
{%block content %}
<p>Learning Languages</p>
<p>Learning Languages helps you learn foreign languages.<p>
{% endblock content %}

learning_foreign_languages/templates/learning_foreign_languages/language.html
{% extends "learning_foreign_languages/base.html" %}

{%block content %}

  <p>Languages</p>

  <ul>
      {% for language in languages %}
        <li>
            <a href="{% url 'learning_foreign_languages:language' language.id %}">{{ language }}</a>
        </li>
      {%empty %}
        <li>No languages have been added yet.</li>
      {% endfor %}
  </ul>
{% endblock content %}

learning_foreign_languages/templates/learning_foreign_languages/languages.html
{% extends "learning_foreign_languages/base.html" %}

{%block content %}

  <p>Languages: {{ language }}</p>

    <p>Vocabulary:</p>
  <ul>
      {% for vocabulary in Vocabularies %}
        <li>
            <p>{{ vocabulary.date_added|date:'M d, Y H:i' }}</p>
            <p>{{vocabulary.text|linebreaks }}</p>
        </li>
      {%empty %}
        <li>
            No languages have been added yet.
        </li>
      {% endfor %}
  </ul>

{% endblock content %}